### ISSUE TITLE
Support Pulumi Deployment configuration via code

### ISSUE THREAD

**Issue by agibralter** [pulumi/service-requests#195]
Currenty Pulumi Deployments can be configured in the UI and via REST API. It'd be nice if you could configure all the Deployments via a YAML file in the repo. E.g. `Pulumi-Deployments.yaml`:

```yaml
deployments:
  - dir: project-1
    prerun: |
      curl -sSL https://install.python-poetry.org | python3.10
      poetry install --directory=/deployment
    skip_automatic_dep_install: true
    custom_image: ...
    oidc:
      aws:
        arn: ...
        session_name: ...
        policy_arns: []
    env:
  - dir: project-2
  - dir: group-3/project-3a
  - dir: group-3/project-3b
```

Would something like that make sense or be possible? I guess there would be some complexity depending on whether the projects are all defined in a single repo vs. defined in multiple repos... Make it would make sense to define the deployments right in the Pulumi.yaml stack files?
